// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RommelkoningenApi.Data;

#nullable disable

namespace RommelkoningenApi.Migrations
{
    [DbContext(typeof(AfvalDbContext))]
    partial class AfvalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RommelkoningenApi.Models.AfvalData", b =>
                {
                    b.Property<Guid>("Afval_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Afval_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Confidence")
                        .HasColumnType("real");

                    b.Property<Guid>("Foto_Id")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Afval_Id");

                    b.HasIndex("Foto_Id");

                    b.ToTable("AfvalData", (string)null);
                });

            modelBuilder.Entity("RommelkoningenApi.Models.FotoData", b =>
                {
                    b.Property<Guid>("Foto_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Camera_Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum_En_Tijd")
                        .HasColumnType("datetime2");

                    b.Property<float>("Latitude")
                        .HasColumnType("real");

                    b.Property<float>("Longitude")
                        .HasColumnType("real");

                    b.Property<string>("Postcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Weer_Omschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("temperatuur")
                        .HasColumnType("int");

                    b.Property<string>("windrichting")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Foto_Id");

                    b.ToTable("FotoData", (string)null);
                });

            modelBuilder.Entity("RommelkoningenApi.Models.AfvalData", b =>
                {
                    b.HasOne("RommelkoningenApi.Models.FotoData", null)
                        .WithMany()
                        .HasForeignKey("Foto_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
